const swaggerJSDoc = require('swagger-jsdoc');
const swaggerUi = require('swagger-ui-express');

const swaggerOptions = {
    definition: {
        openapi: '3.0.0',
        info: {
            title: 'Restaurant Service API',
            version: '1.0.0',
            description: 'Restaurant Service API documentation generated by Swagger',
        },
        servers: [
            {
                url: 'http://localhost:3001/api/v1',
                description: 'Local development server',
            },
        ],
    },
    apis: ['./src/routes/*.js'],
};

const swaggerSpec = swaggerJSDoc(swaggerOptions);

module.exports = {
    swaggerUi,
    swaggerSpec,
    swaggerOptions,
};